### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/healvis#21]
The following line isn't being called when I run this on Oscar, which means there's no way of knowing the current progress of a simulation.

https://github.com/RadioAstronomySoftwareGroup/healvis/blob/89182332b353e89b0cd067e7147176b28eceba0f/healvis/observatory.py#L242

**Comment by nkern** [comment]
Interesting, I get that when I set `Nproc > 1`, but don't if `Nproc == 1`

**Comment by aelanman** [comment]
It may be some quirk in the latest version of `multiprocessing`... this isn't an especially urgent issue. Technically subprocesses aren't supposed to communicate with stdout, so this line is kindof a cheat anyway.

**Comment by aelanman** [comment]
This has been fixed -- The process "name" attribute was behaving strangely when names were not strings. That was preventing the zeroth process from printing.
